---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - kubebenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - kubebenches/finalizers
  verbs:
  - update
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - kubebenches/status
  verbs:
  - get
  - patch
  - update
